### ISSUE TITLE
举手，我有问题

### ISSUE THREAD

**Issue by hwanpenn** [moevis/what-is-my-girlfriend-thinking#2]
我们这种模型不管最后有没有识别都会强行分类，比如我们1234四个类，这个时候我做了5，他会强行把我们分到1234中去，其实这种时候最好的结果应该是未识别或者是others，所以我想，能不能增加一个未识别的功能， 另外能不能有一个新增新分类的功能，就是如果我做表情5识别出来是other的话，这个时候可以输入框新增一个分类，然后拍照表情5，然后重新训练完（样本5retrained），最好可以识别类别5， 我看了谷歌工程师有这样实现，试着去模仿一个，但是我自己一个人搞不来，不知道大神们能不能搞定

**Comment by moevis** [comment]
恩，可以考虑这样做，我之所以不做动态添加分类是因为几个框之间的线是用 svg 画的，如果要加分类的话，需要在布局上稍微有所调整。当然，这个坑等我有空时候填（逃
